### ISSUE TITLE
infinite scrolling

### ISSUE THREAD

**Issue by elghomariayoub** [ColorlibHQ/gentelella#705] opened 2018-06-19 08:20 UTC
I had this weird issue where the DIV min height is increasing infinitely.
![custom](https://user-images.githubusercontent.com/37816218/41585606-7be344f2-73a2-11e8-84a4-c7f48b257d1b.JPG)

**Comment by AndreiCN** [comment] 2018-07-19 10:07
Hi there, still encounter that issue ? If you do, can you please provide some more details in order to help you or if you have no further questions, please close the ticket.

**Comment by martinmurciego** [comment] 2018-09-03 13:54
I have same or similar issue: [735](https://github.com/puikinsh/gentelella/issues/735#issue-356512458)

**Comment by Especially** [comment] 2018-09-24 20:32
Ongoing issue from 2016: 
Duplicate of 208#

**Comment by Especially** [comment] 2018-09-24 20:51
I did fix this issue by adjusting my custom.js file (I am _not_ using the minified file) by changing the 
`		footerHeight = $BODY.hasClass('footer_fixed') ? -10 : $FOOTER.height(),
		leftColHeight = $LEFT_COL.eq(1).height() + $SIDEBAR_FOOTER.height(),;`
to
`		footerHeight = $BODY.hasClass('footer_fixed') ? -10 : $FOOTER.outerHeight(),
		leftColHeight = $LEFT_COL.eq(1).height() + $SIDEBAR_FOOTER.outerHeight(),;`

**Comment by sublimedatasys** [comment] 2019-09-23 10:54
@elghomariayoub  Please close the issue if you get your issue resolved. If not refer issue no #735 and #208, Thanks.

**Closed** 2019-09-24 12:45 UTC
Labels: help wanted
