### ISSUE TITLE
Page length automatically increases as data in datatable increases ..

### ISSUE THREAD

**Issue by khushal21** [ColorlibHQ/gentelella#675] opened 2018-04-04 12:23 UTC
I have a item form and a datatable below that which shows the item details. As the item entry increases the empty space at the end of the page increases the page length. It don't show any error. You can see the scroll bar in below image that where it is. 

![capture](https://user-images.githubusercontent.com/25398538/38306953-cc1f4f96-382f-11e8-9cb3-e60dcd00eeca.PNG)

This is the end of the page.

![capture1](https://user-images.githubusercontent.com/25398538/38307023-fba408ec-382f-11e8-940b-43f43b9a5f9e.PNG)

**Comment by khushal21** [comment] 2018-04-05 04:25
Hey William, I understood the cause of the problem and also found the custom.js file. But i didn't understood how to solve it. Can you explain it some more that what should I do with that file or that function.

**Comment by razvanaldea89** [comment] 2019-02-20 07:16
Please see #689

**Comment by cristianraiber** [comment] 2019-02-20 08:31
Duplicate of #689

**Closed by cristianraiber** 2019-02-20 08:31 UTC
