### ISSUE TITLE
Multilevel menu - second level

### ISSUE THREAD

**Issue by rijad** [ColorlibHQ/gentelella#532] opened 2017-07-14 05:30 UTC
When you collapse side menu (only icons shown) second level of multilevel menu is not working properly.

**Comment by AndreiCN** [comment] 2017-07-14 08:20
What you mean by "nok working properly" ?  Can you provide a screenshot ?

**Comment by rijad** [comment] 2017-07-14 09:13
When I click here menu just closes, it shoupd show submenu as it is shown when sidemenu is expanded
![menu](https://user-images.githubusercontent.com/1540486/28206214-5816b44c-6885-11e7-8000-b7418d31dc4b.jpg)

**Comment by AndreiCN** [comment] 2017-07-14 09:49
That's already solved and will be available with 1.5 update, thank you for reporting this though 👍

**Comment by jaimestuardo** [comment] 2019-03-13 21:31
Hello, this was not solved, and in fact, when I load the demo page at https://colorlib.com/polygon/gentelella/, then collapse the menu by using the icon on the top, then click on "Multilevel Menu" and finally, click on "Level One" that has the submenu. The menu is closed, instead of expanding the submenu.

Regards
Jaime

**Comment by cristianraiber** [comment] 2019-03-14 10:19
It looks like this was actually never released or fixed by @AndreiCN

**Comment by William-H-M** [comment] 2019-03-14 12:09
@cristianraiber #490 has more info about this and a proposed solution, so this could be labeled as a duplicate

**Comment by cristianraiber** [comment] 2019-03-14 16:33
duplicate of #490

**Closed by cristianraiber** 2019-03-14 16:33 UTC
Labels: duplicate
