### ISSUE TITLE
blank page print

### ISSUE THREAD

**Issue by viantoro** [ColorlibHQ/gentelella#766] opened 2018-12-11 02:15 UTC
![image](https://user-images.githubusercontent.com/6949617/49773818-23245100-fd25-11e8-9acc-9a85237901f9.png)

please help...
after i press ctrl + p, i got blank page...

**Comment by razvanaldea89** [comment] 2019-02-13 06:03
Can't seem to replicate issue.

**Comment by sublimedatasys** [comment] 2019-09-23 10:27
Ctrl + P will print that current page as per chrome default behavior. We are unable to reproduce this. We can go ahead and close this.

**Closed** 2019-09-24 12:50 UTC
Labels: done
