### ISSUE TITLE
Demo sidebar glitch

### ISSUE THREAD

**Issue by afeique** [ColorlibHQ/gentelella#893] opened 2020-06-19 17:20 UTC
Hello -- just wanted to say, this is an excellent theme.

Windows 10 Build 19631
Chrome 83.0.4103.106 (Official Build) (64-bit)

There is an issue with the demo: it appears like there is a 1px border-left for all sidebar ul > li elements:

![image](https://user-images.githubusercontent.com/766889/85162611-80e90180-b216-11ea-8b4b-6fcc0b71d258.png)

**Comment by William-H-M** [comment] 2020-06-19 18:23
Is just the demo and not the code, this was fixed on #842, demo page hasn't been updated y eons

**Comment by ashot11091950** [comment] 2020-07-03 09:01
> Is just the demo and not the code, this was fixed on #842, demo page hasn't been updated in eons

Please can you also contact them to update demo, because it is the only page with full information about usage, and when something not correct Front developers can't understand which is the right usage of the block, or if something not same with the local and demo, we can't understand the problem is in our part or in the demo.

**Comment by William-H-M** [comment] 2020-07-03 15:57
@puikinsh can you do something about this? So it's possible to update the project page?

**Comment by afeique** [comment] 2020-07-03 20:45
I agree with @ashot11091950. It would be good to have the demo updated and fixed so developers and people researching frameworks have a clear example to copy from.

**Comment by puikinsh** [comment] 2020-07-08 13:49
Demo updated

**Closed by puikinsh** 2020-07-08 13:49 UTC

**Comment by ashot11091950** [comment] 2020-07-09 14:48
> Demo updated

Seems you forgot to purge cloudflare cache
![image](https://user-images.githubusercontent.com/40325246/87054904-b761dd00-c214-11ea-9b17-57d9e47878b4.png)
