### ISSUE TITLE
The project demo has a code conflict

### ISSUE THREAD

**Issue by LittleYellowMonster** [ColorlibHQ/gentelella#809] opened 2019-09-03 08:55 UTC
![1567500591(1)](https://user-images.githubusercontent.com/25114935/64158709-8d5cc300-ce6b-11e9-9176-6321f90cbb95.jpg)

**Comment by William-H-M** [comment] 2019-09-03 12:05
Duplicate of #433 
Please close this

**Closed** 2019-09-12 07:26 UTC
